#! /bin/sh

/bin/sh ~/dotfiles/scripts/autostart.sh

bspc monitor -d I II III IV

bspc config focused_border_color "#4E6698"
bspc config normal_border_color "#6D7275"

bspc config border_width         1
bspc config window_gap          30
bspc config top_padding         30

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 resize_corner
bspc config focus_follows pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Plasma state=floating manage=off layer=normal
bspc rule -a Plasma-desktop state=floating
bspc rule -a plasmashell sticky=on layer=above state=floating
