" Source other vim setting files
source ~/dotfiles/vimrc/mappings.vim
source ~/dotfiles/vimrc/colours.vim

" Set 'nocompatible' to ward off unexpected things that your distro might
" have made, as well as sanely reset options when re-sourcing .vimrc
set nocompatible
 
" Attempt to determine the type of a file based on its name and possibly its
" contents. Use this to allow intelligent auto-indenting for each filetype,
" and for plugins that are filetype specific.
filetype indent plugin on
 
" Enable syntax highlighting
syntax enable

" Better command-line completion
set wildmenu
 
" Show partial commands in the last line of the screen
set showcmd
 
" No highlighting text when searching
set nohlsearch

" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase
 
" Allow backspacing over autoindent, line breaks and start of insert action
set backspace=indent,eol,start
 
" When opening a new line and no filetype-specific indenting is enabled, keep
" the same indent as the line you're currently on. Useful for READMEs, etc.
set autoindent
 
" Sow cursor position in line of a window
set ruler
 
" Always display the status line, even if only one window is displayed
set laststatus=2
 
" Confirm exit with chance to save
set confirm
 
" Use visual bell instead of beeping when doing something wrong
set visualbell
 
" Set the command window height to 2 lines, to avoid many cases of having to
" "press <Enter> to continue"
set cmdheight=2
 
" Display line numbers on the left
set number
set relativenumber
 
" Quickly time out on keycodes, but never time out on mappings
set notimeout ttimeout ttimeoutlen=200
 
" Use <F11> to toggle between 'paste' and 'nopaste'
set pastetoggle=<F11>
 
" Indentation options
set shiftwidth=4
set softtabstop=4
set tabstop=8
set expandtab

" Other settings, need to find out what they do
set incsearch
set t_Co=16
